### ISSUE TITLE
CLI-876: ACLI should not fail with an error when refresh tokens are missing

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1219]
When refresh tokens are missing (e.g. locally in dev) ACLI fails immediately:

```
ide:~/project $ acli --version

Fatal error: Uncaught Acquia\Cli\Exception\AcquiaCliException: Access token file not found at /usr/local/share/ide/.accesstoken in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php:36
Stack trace:
#0 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getConnectorFactoryService.php(20): Acquia\Cli\CloudApi\CloudCredentials->getCloudAccessToken()
#1 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getConnectorFactoryService::do()
#2 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getClientServiceService.php(26): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#3 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getClientServiceService::do()
#4 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getTelemetryHelperService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#5 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getTelemetryHelperService::do()
#6 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getAcsfApiAuthLoginCommandService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#7 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getAcsfApiAuthLoginCommandService::do()
#8 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getApplicationService.php(33): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#9 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getApplicationService::do()
#10 phar:///opt/local/acli/vendor/symfony/dependency-injection/Container.php(215): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#11 phar:///opt/local/acli/vendor/symfony/dependency-injection/Container.php(197): Symfony\Component\DependencyInjection\Container->make()
#12 phar:///opt/local/acli/bin/acli(84): Symfony\Component\DependencyInjection\Container->get()
#13 /opt/local/acli(14): require('...')
#14 {main}
  thrown in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 36
```

If you create empty `/usr/local/share/ide/.accesstoken` and `/usr/local/share/ide/.expirytoken` files, the error goes away immediately. This is indicative of an issue because if we check for files, we're not checking that content within actually exists, and this means we can lure ACLI into thinking all is well.

Additionally, we know an alternative to checking for refresh tokens is to check for manual authentication. But this will also fail despite `~/.acquia/cloud_api.conf` being available (and valid) or not.

```
ide:~/project $ acli auth:login

Fatal error: Uncaught Acquia\Cli\Exception\AcquiaCliException: Access token file not found at /usr/local/share/ide/.accesstoken in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php:36
Stack trace:
#0 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getConnectorFactoryService.php(20): Acquia\Cli\CloudApi\CloudCredentials->getCloudAccessToken()
#1 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getConnectorFactoryService::do()
#2 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getClientServiceService.php(26): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#3 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getClientServiceService::do()
#4 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getTelemetryHelperService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#5 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getTelemetryHelperService::do()
#6 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getAcsfApiAuthLoginCommandService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#7 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getAcsfApiAuthLoginCommandService::do()
#8 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/getApplicationService.php(33): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#9 phar:///opt/local/acli/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getApplicationService::do()
#10 phar:///opt/local/acli/vendor/symfony/dependency-injection/Container.php(215): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#11 phar:///opt/local/acli/vendor/symfony/dependency-injection/Container.php(197): Symfony\Component\DependencyInjection\Container->make()
#12 phar:///opt/local/acli/bin/acli(84): Symfony\Component\DependencyInjection\Container->get()
#13 /opt/local/acli(14): require('...')
#14 {main}
  thrown in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 36
```

**Comment by danepowell** [comment]
I think we agreed that this is the intended behavior. This exception only occurs if the customer environment sets ACLI_ACCESS_TOKEN_FILE. If that variable is set incorrectly, an exception is the appropriate response. If the customer explicitly set that, they need to fix it. If it's IDEs setting that incorrectly, we need to fix it in IDEs.
