### ISSUE TITLE
CLI-877: Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1226]
I was trying to hack into a test IDE (not mine) to test a command with the latest ACLI. Got this:

```
ide:/tmp $ /usr/local/php8.1/bin/php acli.phar

Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "token" under "cloud_api". Available options are "acli_key", "acsf_active_factory", "acsf_factories", "keys", "send_telemetry", "user". in phar:///tmp/acli.phar/vendor/symfony/config/Definition/ArrayNode.php:322
Stack trace:
#0 phar:///tmp/acli.phar/vendor/symfony/config/Definition/BaseNode.php(352): Symfony\Component\Config\Definition\ArrayNode->normalizeValue()
#1 phar:///tmp/acli.phar/vendor/symfony/config/Definition/Processor.php(32): Symfony\Component\Config\Definition\BaseNode->normalize()
#2 phar:///tmp/acli.phar/vendor/symfony/config/Definition/Processor.php(46): Symfony\Component\Config\Definition\Processor->process()
#3 phar:///tmp/acli.phar/src/DataStore/Datastore.php(85): Symfony\Component\Config\Definition\Processor->processConfiguration()
#4 phar:///tmp/acli.phar/src/DataStore/JsonDataStore.php(31): Acquia\Cli\DataStore\Datastore->processConfig()
#5 phar:///tmp/acli.phar/src/DataStore/CloudDataStore.php(34): Acquia\Cli\DataStore\JsonDataStore->__construct()
#6 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getCloudDataStoreService.php(20): Acquia\Cli\DataStore\CloudDataStore->__construct()
#7 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getCloudDataStoreService::do()
#8 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getCloud_CredentialsService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#9 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getCloud_CredentialsService::do()
#10 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getConnectorFactoryService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#11 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getConnectorFactoryService::do()
#12 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getClientServiceService.php(26): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#13 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getClientServiceService::do()
#14 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getTelemetryHelperService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#15 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getTelemetryHelperService::do()
#16 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getAcsfApiAuthLoginCommandService.php(20): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#17 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getAcsfApiAuthLoginCommandService::do()
#18 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/getApplicationService.php(33): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#19 phar:///tmp/acli.phar/var/cache/prod/ContainerTpfgm3l/Acquia_Cli_KernelProdContainer.php(181): ContainerTpfgm3l\getApplicationService::do()
#20 phar:///tmp/acli.phar/vendor/symfony/dependency-injection/Container.php(215): ContainerTpfgm3l\Acquia_Cli_KernelProdContainer->load()
#21 phar:///tmp/acli.phar/vendor/symfony/dependency-injection/Container.php(197): Symfony\Component\DependencyInjection\Container->make()
#22 phar:///tmp/acli.phar/bin/acli(84): Symfony\Component\DependencyInjection\Container->get()
#23 /tmp/acli.phar(14): require('...')
#24 {main}
  thrown in phar:///tmp/acli.phar/vendor/symfony/config/Definition/ArrayNode.php on line 322
```

Can we fail more gracefully?

**Comment by danepowell** [comment]
We need to figure out where the "token" is coming from. If someone was just hacking on their config file, we are right to throw an error due to an invalid key. But if this is being generated regularly by some Acquia product that we're not aware of, then yes we should accommodate it.

**Comment by anavarre** [comment]
This is way simpler, actually. Tried to troubleshoot an IDE, wanted to test a command with the latest ACLI version and got this.

**Comment by danepowell** [comment]
Are you saying this is only an issue with the latest version of ACLI?

The error is telling you that cloud_api.conf contains an invalid key called "token". AFAIK that is indeed an invalid key, meaning that a customer hacked it into the file manually (not our fault), or some other product is writing to that file in a way that we aren't aware of.
