### ISSUE TITLE
CLI-878: Force IDE SSH key to be owned by root and recommend using the Configure IDE button

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1227]
If you remove `id_rsa_acquia_ide_<REMOTEIDE_UUID>` and create your own `id_rsa(.pub)` combination with a passphrase that is not added to the `ssh-agent` and `keychain`, upon unhibernating the proxy container will fail to load the IDE and will fail with this error at the `/health` endpoint:

```
{"message":"connect ECONNREFUSED 127.0.0.1:3000","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:3000\n    at Function.AxiosError.from (/usr/src/app/node_modules/axios/dist/node/axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (/usr/src/app/node_modules/axios/dist/node/axios.cjs:2465:25)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest.emit (domain.js:475:12)\n    at ClientRequest.eventHandlers.<computed> (/usr/src/app/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at Socket.socketErrorListener (_http_client.js:475:9)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.1.2","Accept-Encoding":"gzip, deflate, br"},"method":"get","url":"http://127.0.0.1:3000"},"code":"ECONNREFUSED","status":null}
```

This is because since we have fixed the Theia Git UI issue, it is critical for Theia to find a key to load automatically so the plugin works. When customers manually create keys without using `ide:wizard:ssh-key:create-upload` they will not know it's required, leading to this situation.

One issue is on Cloud IDE to fix, by strongly recommending people use the wizard command instead of `ssh-keygen` (but not block them from doing so since there are valid use cases). Other issues are on ACLI to fix:

* Ensure the wizard commands takes care of changing ownership of those keys to `root` since there's no obvious use case that warrants ever deleting those keys
* Ensure `ssh-key:create-upload` also prompts users to use "Configure IDE" button instead, without blocking them from performing this operation if they want to.

Note: in https://github.com/acquia/cli/blob/83dfb30525e7f7bea326c3cc53b00566f2474d68/src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php#L57-L60 we'll probably have to refactor the code a bit since we won't be able to remove the keys anymore.

**Comment by anavarre** [comment]
Instead of doing that, let's pre-provision SSH keys so the ACLI operation just consists of uploading the SSH key to the Cloud Platform.
