### ISSUE TITLE
Issues refreshing ACSF sites

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#227]
<img width="886" alt="ide-acsf" src="https://user-images.githubusercontent.com/293478/90101643-64150a00-dd3f-11ea-8310-75480128bc65.PNG">

@danepowell this one looks critical as it's blocking an ACSF customer from pulling the site locally.

**Comment by anavarre** [comment]
I reproduced against a test ACSF sub

```
ide:~/project$ acli refresh
Using Cloud Application <REDACTED>
Choose an Acquia Cloud environment to copy from:
  [0] 01dev (vcs: develop)
  [1] 01_test (vcs: composer-refactor-070920)
 > 1
    ✔ Pulling code from Acquia Cloud
{"cloud":{"site":"<REDACTED>","env":"01_test"},"memcache_inc":"profiles\/gardens\/modules\/acquia\/memcache\/memcache.inc",
"sites": {
"<REDACTED>.acsitefactory.com": {"name":"<REDACTED>test","flags":{"preferred_domain":true},"conf":{"gardens_site_id":<REDACTED>,"gardens_db_name":"REDACTEDtest","acsf_site_id":<REDACTED>,"acsf_db_name":"<REDACTED>test","site_api_key":"<REDACTED>"}}
}}
PHP Fatal error:  Uncaught TypeError: Return value of Acquia\Cli\Command\RefreshCommand::getAcsfSites() must be of the type array, null returned in phar:///usr/local/bin/acli/src/Command/RefreshCommand.php:572
Stack trace:
#0 phar:///usr/local/bin/acli/src/Command/RefreshCommand.php(397): Acquia\Cli\Command\RefreshCommand->getAcsfSites(Object(AcquiaCloudApi\Response\EnvironmentResponse))
#1 phar:///usr/local/bin/acli/src/Command/RefreshCommand.php(534): Acquia\Cli\Command\RefreshCommand->promptChooseDatabase(Object(AcquiaCloudApi\Response\EnvironmentResponse), Array)
#2 phar:///usr/local/bin/acli/src/Command/RefreshCommand.php(92): Acquia\Cli\Command\RefreshCommand->determineSourceDatabase(Object(AcquiaCloudApi\Connector\Client), Object(AcquiaCloudApi\Response\EnvironmentResponse))
#3 phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php(258): Acquia\Cli\Command\RefreshCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local in phar:///usr/local/bin/acli/src/Command/RefreshCommand.php on line 572
```
