### ISSUE TITLE
Phar not generated for 1.7.1

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#437]
https://travis-ci.com/github/acquia/cli/builds/218375416

```
/ $ acli --version
Acquia CLI 1.6.0
/ $ acli self-update
PHP Notice:  Undefined offset: 0 in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 94
PHP Notice:  Trying to get property 'browser_download_url' of non-object in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 94
Downloading Acquia CLI (acquia/cli) 1.7.1
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Filesystem\Filesystem::copy() must be of the type string, null given, called in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 150 and defined in phar:///opt/local/acli/vendor/symfony/filesystem/Filesystem.php:37
Stack trace:
#0 phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php(150): Symfony\Component\Filesystem\Filesystem->copy()
#1 phar:///opt/local/acli/vendor/symfony/console/Command/Command.php(255): SelfUpdate\SelfUpdateCommand->execute()
#2 phar:///opt/local/acli/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run()
#3 phar:///opt/local/acli/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///opt/local/acli/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#5 phar:///opt/local/acli/bin/acli(88): Symfony\Component\Console\Application-> in phar:///opt/local/acli/vendor/symfony/filesystem/Filesystem.php on line 37
```

**Comment by danepowell** [comment]
I've manually built and attached a phar for now. The root cause is a Composer change, I'll open a PR with a fix and tests.
