### ISSUE TITLE
CLI-739: api:applications:environment-create breaks if provides all arguments/options.

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#907]
Error -
```
Fatal error: Uncaught TypeError: Argument 2 passed to Acquia\Cli\Command\Api\ApiCommandBase::castParamType() must be of the type string, array given, called in /src/Command/Api/ApiCommandBase.php on line 406 and defined in /src/Command/Api/ApiCommandBase.php:242
Stack trace:
#0 /src/Command/Api/ApiCommandBase.php(406): Acquia\Cli\Command\Api\ApiCommandBase->castParamType(Array, Array)
#1 /src/Command/Api/ApiCommandBase.php(391): Acquia\Cli\Command\Api\ApiCommandBase->addPostParamToClient('databases', Array, Array, Object(AcquiaCloudApi\Connector\Client))
#2 /src/Command/Api/ApiCommandBase.php(109): Acquia\Cli\Command\Api\ApiCommandBase->addPostParamsToClient(Object(Symfony\Component\Console\Input\ArgvInput), Object(AcquiaCloudApi\Connector\Client))
#3 /vendor/symfony/console/Command/Command.php(298): Acquia\Cl in /src/Command/Api/ApiCommandBase.php on line 242
```

Steps for reproduce -
```
/acli api:applications:environment-create @someenvname "Test" main-code-studio d1
```

**Comment by joshirohit100** [comment]
It looks like happening because of database values seems array -
```
api:applications:environment-create @eerjoshi.dev "Test" main-code-studio d1
string(4) "Test"
string(16) "main-code-studio"
array(1) {
  [0]=>
  string(2) "d1"
}
```
