### ISSUE TITLE
CLI-761: Fatal PHP error when using app:environment:mirror

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#989]
```
❯ acli app:environment:mirror jane.dev jane.test
    ✔ Fetching information about source environment
    ✔ Fetching information about destination environment

 Are you sure that you want to overwrite everything on Stage (test) and replace it with source data from Dev (dev) (yes/no) [yes]:
 > yes

    ✔ Initiating code switch
    ✔ Initiating database copy
    ✔ Initiating files copy
    ✔ Initiating config copy
PHP Warning:  Undefined property: stdClass::$links in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825

Warning: Undefined property: stdClass::$links in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825
PHP Warning:  Attempt to read property "notification" on null in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825

Warning: Attempt to read property "notification" on null in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825
PHP Warning:  Attempt to read property "href" on null in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825

Warning: Attempt to read property "href" on null in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1825
PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1826

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1826
PHP Warning:  Undefined array key 5 in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1827

Warning: Undefined array key 5 in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1827
PHP Fatal error:  Uncaught TypeError: Acquia\Cli\Command\CommandBase::getNotificationUuidFromResponse(): Return value must be of type string, null returned in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php:1827
Stack trace:
#0 /Users/jane/Git/acquia/cli/src/Command/App/EnvironmentMirrorCommand.php(92): Acquia\Cli\Command\CommandBase->getNotificationUuidFromResponse(Object(stdClass))
#1 /Users/jane/Git/acquia/cli/vendor/symfony/console/Command/Command.php(291): Acquia\Cli\Command\App\EnvironmentMirrorCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/jane/Git/acquia/cli/src/Command/CommandBase.php(386): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(1007): Acquia\Cli\Command\CommandBase->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Acquia\Cli\Command\App\EnvironmentMirrorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/jane/Git/acquia/cli/bin/acli(77): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
  thrown in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1827

Fatal error: Uncaught TypeError: Acquia\Cli\Command\CommandBase::getNotificationUuidFromResponse(): Return value must be of type string, null returned in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php:1827
Stack trace:
#0 /Users/jane/Git/acquia/cli/src/Command/App/EnvironmentMirrorCommand.php(92): Acquia\Cli\Command\CommandBase->getNotificationUuidFromResponse(Object(stdClass))
#1 /Users/jane/Git/acquia/cli/vendor/symfony/console/Command/Command.php(291): Acquia\Cli\Command\App\EnvironmentMirrorCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/jane/Git/acquia/cli/src/Command/CommandBase.php(386): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(1007): Acquia\Cli\Command\CommandBase->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Acquia\Cli\Command\App\EnvironmentMirrorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/jane/Git/acquia/cli/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/jane/Git/acquia/cli/bin/acli(77): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
  thrown in /Users/jane/Git/acquia/cli/src/Command/CommandBase.php on line 1827
```

**Comment by grasmash** [comment]
I can't reproduce this.
